version: "2"
services:
  cronjobber:
            # image: hchstera/alpine-php-cron:latest
            image: docker
            volumes:
              - /var/run/docker.sock:/var/run/docker.sock
              - ./docker/cron/crontab:/etc/cron.d
              - ./docker/cron/log:/var/log/cron
            container_name: cronjobber
            command: >
                  sh -c "
                  echo '* * * * * docker exec -t php php yii2.docker/yii hello' > /etc/cron.d
                  && crond -f -d 8"