<?php


namespace app\modules\alexadmx\controllers;

use Yii;
use yii\web\Controller;
use app\modules\alexadmx\models\Msg;

class AppAlexadmxController extends Controller
{
    public function beforeAction($action)
    {
//        debug(Yii::$app->requestedAction->id);
// * Количество новых(не помеченных как прочитанные) сообщений
// * (boolean поле "is_read" в таблицах post и callback в ответе за это)
        $arr = Msg::getNewMsgCount();
        $session = Yii::$app->session;

        $session->set('newPostCount', $arr['newPostCount']);
        $session->set('newCallCount', $arr['newCallCount']);
// * Количество всех сообщений
        $arr = Msg::getAllMsgCount();
        $session->set('allPostCount', $arr['allPostCount']);
        $session->set('allCallCount', $arr['allCallCount']);
//debug($_SESSION['newCallCount']);
//die;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}